import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode; // Simple typing for children
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
      
     
       {children}

        <Footer /> {/* Footer inside the body */}
      </body>
    </html>
  );
}
